### ISSUE TITLE
nao consiquiu testa

### ISSUE THREAD

**Issue by marcelowu** [dholidev/module-dholi-theme-frontend-mirror#1]
![Capturar10](https://user-images.githubusercontent.com/30912144/72647744-fe52d200-3957-11ea-87c0-ed34cf190d89.PNG)

**Comment by dholidev** [comment]
Marcelo, basta rodar o comando "setup:upgrade" novamente, irá instalar.

No final, antes de rodar a compilação, verifique a tabela "theme", o valor da coluna "type" deve ser "0", como as demais linhas.

* Hover Image
Para vincular a imagem hover é preciso vincular o atributo em cada grupo de atributo, limpar a cache e em cada imagem, vincular a mesma com "Hover Image".

* Pacote de componentes
Neste repo https://packagist.org/packages/dholi/module-dholi-widgets tem alguns componentes que poderá usar com o tema.

Vou reforçar com você, está usando versões de desenvolvimento. Não use essas versões me PRODUÇÃO.

**Comment by marcelowu** [comment]
o
